package com.codecafe.grpc.protobuf;

import com.codecafe.grpc.protobuf.model.Person;

public class PersonProtoDemo {

    public static void main(String[] args) {

        // The generated file allows only to use
        // the Builder in order to create an instance

        Person john = Person.newBuilder()
                .setName("John Wick")
                .setAge(42)
                .setEmail("john.wick@xyz.com")
                .build();

        System.out.println(john);

        // We cannot override the equals() method
        // that is generated by the proto plugin

        Person tom1 = Person.newBuilder()
                .setName("tom")
                .setAge(42)
                .build();

        Person tom2 = Person.newBuilder()
                .setName("tom")
                .setAge(42)
                .build();

        Person tom3 = Person.newBuilder()
                .setName("Tom")
                .setAge(42)
                .build();

        System.out.println("tom1:\n" + tom1);
        System.out.println("tom2:\n" + tom2);
        System.out.println("tom3:\n" + tom3);

        System.out.println("tom1 == tom2 : " + (tom1 == tom2)); // false
        System.out.println("tom1.equals(tom2) : " + tom1.equals(tom2)); // true

        System.out.println("tom1.equals(tom3) : " + tom1.equals(tom3)); // false
    }

}